name: rust

on: [push, pull_request]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
        toolchain: [ stable, 1.28.0, nightly ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.platform }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --verbose --all
