name: rust

on: [push, pull_request]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
        toolchain: [ stable, 1.28.0, nightly ]
        project_dir: [ ".", "no_std" ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: Build Project
        working-directory: ${{ matrix.project_dir }}
        run: cargo build --release --all-features
